## Python For Machine Learning Fall 2025
---
# Tensors to CNN in PyTorch

The intension of this notebook is to walk you through the fundamental concepts of PyTorch, and build your first neural network to classify handwritten digits.

# 1. PyTorch?

PyTorch is a popular open-source machine learning library developed primarily by Facebook's AI Research lab (FAIR). It's loved by researchers and developers for two main reasons:

1.  **Tensor Computing**: It provides a powerful N-dimensional Tensor (like a NumPy array) that can be accelerated on GPUs.
2.  **Dynamic Computation Graph**: Unlike some other frameworks, PyTorch builds a graph of computations "on the fly." This makes debugging easier and allows for more flexible model architectures.

## 1.1 The Evolution of Deep Learning Frameworks
The development of deep learning frameworks over the past few decades has been a story of evolving abstractions, driven by the need for greater flexibility, faster performance, and easier debugging. This evolution can be broadly categorized into distinct eras, culminating in the powerful, dynamic frameworks we use today.

### 1.1.1 Scientific Computing Before Deep Learning

Before the deep learning boom, researchers built models from scratch or used general scientific computing libraries. The first specialized frameworks emerged from academia to simplify this process.

* **Torch (2002):** An open-source scientific computing framework with a scripting language based on **LuaJIT**. Developed at IDIAP, it was powerful and flexible, gaining popularity in research labs (notably at NYU, and later, Facebook AI Research). It laid the groundwork for its successor, PyTorch.
* **Theano (2007):** Developed at the University of Montreal (MILA), Theano was a pioneering Python library. Its key innovation was the ability to **define, optimize, and evaluate mathematical expressions, especially those with multi-dimensional arrays (tensors)**. It introduced the concept of a **static computation graph**, where the model's architecture was first defined and then compiled for efficient execution on CPUs or GPUs.

### 1.1.2 Static Computational Graph (Define-and-Run)

As deep learning, particularly in computer vision, began to show state-of-the-art results, new frameworks emerged, focusing on speed, scalability, and clear model definitions.

* **Caffe (2013):** Created at UC Berkeley (BVLC), Caffe was renowned for its **blazing speed, especially for training and deploying convolutional neural networks (CNNs)**. It was written in C++ with a Python interface. Models were famously defined in plain-text configuration files (`.prototxt`), which made it easy to share and reproduce models like AlexNet and VGG.
* **Keras (2015):** Developed by François Chollet, Keras was created with a focus on user experience. It acted as a **high-level, user-friendly API** that abstracted away the complexities of the backend. Initially, it ran on top of Theano (and later, TensorFlow), allowing for rapid prototyping and experimentation.
* **TensorFlow (2015):** Released by Google Brain, TensorFlow 1.x became the dominant framework for both research and production. Like Theano, it used a **static computation graph** (a "define-and-run" paradigm). This approach was powerful for optimization and deployment to various platforms (servers, mobile, web), but it was often criticized for being verbose and difficult to debug.

### 1.1.3 Dynamic Computational Graph (Define-by-Run)

A major paradigm shift occurred with the introduction of dynamic computation graphs, which offered a more intuitive and Python-native development experience.

* **PyTorch (2016):** Developed by Facebook's AI Research (FAIR) lab, PyTorch was heavily inspired by Torch but was built from the ground up for Python. Its killer feature was the **dynamic computation graph** (a "define-by-run" paradigm). This meant the graph was built on-the-fly as the code executed, allowing for standard Python control flow (like `if` statements and `for` loops) and making debugging as simple as using a standard Python debugger.
* **The Convergence (2018-2019):** The popularity and developer-friendly nature of PyTorch spurred a change across the ecosystem.
    * In 2018, **Caffe2 (Facebook's production-focused successor to Caffe) was merged into PyTorch**, giving PyTorch a much stronger production and deployment story.
    * In 2019, Google released **TensorFlow 2.0**, which fundamentally changed the framework by **adopting eager execution (a dynamic graph approach) by default** and tightly integrating **Keras as its official high-level API**.

This convergence has led to the current landscape, which is largely dominated by PyTorch and TensorFlow 2.x. Both now offer a flexible, define-by-run experience for research and development, while also providing robust, high-performance graph-based modes for optimized production deployment.

## 1.2 Pytorch vs TensorFlow

For this course, we will use PyTorch as our primary library over TensorFlow. This decision is rooted in PyTorch's design philosophy and its overwhelming popularity, which aligns perfectly with a Python-first learning environment. Put simply, PyTorch feels like a natural extension of Python. Its "define-by-run" paradigm means your code executes line by line, just as you'd expect. This makes debugging a far more intuitive process; you can use standard `print()` statements or Python debuggers to inspect tensors and model components at any point in your code.

This "Pythonic" nature significantly flattens the learning curve for students already familiar with Python and its data science stack. More importantly, PyTorch has become the dominant framework in the AI research community. Recent analyses in 2024 and 2025 show that PyTorch is used in around 85% of deep learning research papers. By learning PyTorch, you are learning the tool of choice for the vast majority of new academic papers and cutting-edge projects, particularly in fast-moving fields like generative AI and natural language processing (NLP), thanks in large part to its deep integration with a robust ecosystem, including libraries like Hugging Face Transformers.

# 2. Tensors

A PyTorch Tensor is the central data structure. It's conceptually similar to a NumPy `ndarray` but with the added ability to run on a GPU to accelerate computations.

First, you'll need to import `torch` and `numpy`.

In [ ]:
import torch
import numpy as np

### 2.1 Creating Tensors

You can create tensors in several ways:

In [ ]:
# Create a tensor from a Python list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor from list:\n {x_data}")

# Create a tensor from a NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"\nTensor from NumPy array:\n {x_np}")

# Create a tensor of all ones
# shape is a tuple (rows, cols)
x_ones = torch.ones((2, 3))
print(f"\nTensor of ones:\n {x_ones}")

# Create a tensor of all zeros
x_zeros = torch.zeros((2, 3))
print(f"\nTensor of zeros:\n {x_zeros}")

# Create a tensor with random values (from 0 to 1)
x_rand = torch.rand((2, 3))
print(f"\nRandom tensor:\n {x_rand}")

Tensor from list:
 tensor([[1, 2],
        [3, 4]])

Tensor from NumPy array:
 tensor([[1, 2],
        [3, 4]])

Tensor of ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Tensor of zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

Random tensor:
 tensor([[0.0587, 0.9256, 0.1577],
        [0.1037, 0.3886, 0.3363]])


## 2.2 Tensor Operations

Operations are very intuitive and have a familiar syntax.



### 2.2.1 Arithmetic

In [ ]:
# Create two tensors
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

# Element-wise addition
c = a + b
print(f"Addition:\n {c}")

# Element-wise multiplication
d = a * b
print(f"\nElement-wise multiplication:\n {d}")

# Matrix multiplication
# Note: @ is the infix operator for matrix multiplication
e = a @ b
print(f"\nMatrix multiplication:\n {e}")

Addition:
 tensor([[ 6,  8],
        [10, 12]])

Element-wise multiplication:
 tensor([[ 5, 12],
        [21, 32]])

Matrix multiplication:
 tensor([[19, 22],
        [43, 50]])


### 2.2.2 Indexing and Slicing

Just like NumPy!

In [ ]:
tensor = torch.rand((4, 3)) # 4 rows, 3 cols
print(f"\nOriginal tensor:\n {tensor}")

# Get the first row
print(f"\nFirst row:\n {tensor[0, :]}")

# Get the last column
print(f"\nLast column:\n {tensor[:, -1]}")


Original tensor:
 tensor([[0.2207, 0.0121, 0.9227],
        [0.5491, 0.2708, 0.9009],
        [0.4885, 0.5656, 0.9116],
        [0.5514, 0.8438, 0.4044]])

First row:
 tensor([0.2207, 0.0121, 0.9227])

Last column:
 tensor([0.9227, 0.9009, 0.9116, 0.4044])


### 2.2.3 Reshaping

The `.view()` method is a powerful way to change shape. `-1` tells PyTorch to infer the dimension.

In [ ]:
flat_tensor = tensor.view(12) # Flattens to a 1D tensor of 12 elements
print(f"\nFlattened (12):\n {flat_tensor}")

# Reshape to 2x6
reshaped_tensor = tensor.view(2, 6)
print(f"\nReshaped (2x6):\n {reshaped_tensor}")

# Reshape to 3x4
reshaped_tensor_auto = tensor.view(3, -1) # -1 infers 4
print(f"\nReshaped (3x-1 -> 3x4):\n {reshaped_tensor_auto}")


Flattened (12):
 tensor([0.2207, 0.0121, 0.9227, 0.5491, 0.2708, 0.9009, 0.4885, 0.5656, 0.9116,
        0.5514, 0.8438, 0.4044])

Reshaped (2x6):
 tensor([[0.2207, 0.0121, 0.9227, 0.5491, 0.2708, 0.9009],
        [0.4885, 0.5656, 0.9116, 0.5514, 0.8438, 0.4044]])

Reshaped (3x-1 -> 3x4):
 tensor([[0.2207, 0.0121, 0.9227, 0.5491],
        [0.2708, 0.9009, 0.4885, 0.5656],
        [0.9116, 0.5514, 0.8438, 0.4044]])


## 2.3 NumPy Bridge

Converting between PyTorch Tensors and NumPy arrays is seamless.

**Important**: The Tensor and NumPy array will share the same underlying memory location on the CPU, so changing one will change the other.

In [ ]:
# --- Tensor to NumPy ---
a = torch.ones(5)
print(f"Original tensor: {a}")
b = a.numpy()
print(f"NumPy array: {b}")

# Modifying the tensor changes the numpy array
a.add_(1) # In-place addition
print(f"Modified tensor: {a}")
print(f"NumPy array (also modified): {b}")

Original tensor: tensor([1., 1., 1., 1., 1.])
NumPy array: [1. 1. 1. 1. 1.]
Modified tensor: tensor([2., 2., 2., 2., 2.])
NumPy array (also modified): [2. 2. 2. 2. 2.]


In [ ]:
# --- NumPy to Tensor ---
a = np.ones(5)
b = torch.from_numpy(a)
print(f"\nOriginal NumPy array: {a}")
print(f"Tensor: {b}")

# Modifying the numpy array changes the tensor
np.add(a, 1, out=a) # In-place addition
print(f"Modified NumPy array: {a}")
print(f"Tensor (also modified): {b}")


Original NumPy array: [1. 1. 1. 1. 1.]
Tensor: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
Modified NumPy array: [2. 2. 2. 2. 2.]
Tensor (also modified): tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## 2.4 GPU Support (CUDA)

This is where PyTorch shines. You can move any tensor to the GPU to perform massively parallel computations.

In [ ]:
# Check if a GPU is available
if torch.cuda.is_available():
    print("CUDA (GPU) is available!")
    # Define a "device" to be our GPU
    device = torch.device("cuda")

    # Create a tensor on the CPU
    x = torch.rand(4, 4)
    print(f"\nTensor on CPU:\n {x}")

    # Move the tensor to the GPU
    y = x.to(device)
    print(f"\nTensor on GPU:\n {y}")

    # Operations can now happen on the GPU
    z = y @ y
    print(f"\nGPU operation result:\n {z}")

    # To bring it back to the CPU, use .to('cpu')
    # Note: You can't convert a GPU tensor directly to NumPy.
    # You must move it to the CPU first.
    try:
        z.numpy()
    except Exception as e:
        print(f"\nError converting GPU tensor to NumPy: {e}")

    z_cpu = z.to("cpu")
    z_np = z_cpu.numpy()
    print(f"\nSuccessfully converted to NumPy after moving to CPU:\n {z_np}")
else:
    print("CUDA (GPU) is not available. Running on CPU.")
    device = torch.device("cpu")

CUDA (GPU) is available!

Tensor on CPU:
 tensor([[0.3112, 0.1436, 0.3467, 0.0208],
        [0.4133, 0.0338, 0.5433, 0.8891],
        [0.7032, 0.9894, 0.9190, 0.5214],
        [0.0937, 0.9419, 0.1587, 0.7969]])

Tensor on GPU:
 tensor([[0.3112, 0.1436, 0.3467, 0.0208],
        [0.4133, 0.0338, 0.5433, 0.8891],
        [0.7032, 0.9894, 0.9190, 0.5214],
        [0.0937, 0.9419, 0.1587, 0.7969]], device='cuda:0')

GPU operation result:
 tensor([[0.4020, 0.4122, 0.5079, 0.3315],
        [0.6080, 1.4355, 0.8020, 1.0304],
        [1.3229, 1.5348, 1.7087, 1.7889],
        [0.6047, 0.9529, 0.8165, 1.5572]], device='cuda:0')

Error converting GPU tensor to NumPy: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Successfully converted to NumPy after moving to CPU:
 [[0.40199155 0.41215152 0.5078788  0.3314632 ]
 [0.607963   1.4354646  0.80203396 1.0303624 ]
 [1.3229002  1.5347592  1.7086949  1.7888646 ]
 [0.6047168  0.9528868  0.8165419

# 3. Autograd - Automatic Differentiation

This is the magic behind how neural networks learn. PyTorch uses a library called `autograd` to automatically compute gradients (derivatives).

## 3.1 How it Works

1.  You create a tensor and set its `requires_grad` attribute to `True`. This tells PyTorch to track all operations performed on it.
2.  You perform some computations (e.g., your model's forward pass).
3.  You get a single scalar value at the end (e.g., your loss).
4.  You call `.backward()` on this scalar.
5.  PyTorch automatically computes the gradient of this scalar with respect to all tensors that had `requires_grad=True`.
6.  The computed gradients are stored in the `.grad` attribute of each tensor.

## 3.2 A Simple Example

Let's find the gradient of $y$ with respect to $x$ for the function $y = 3x^2 + 2$ at $x = 4$.

The derivative is $dy/dx = 6x$. At $x=4$, the gradient should be $6 * 4 = 24$.

In [ ]:
# Create a tensor and tell PyTorch to track it
x = torch.tensor(4.0, requires_grad=True)

# Define the function
y = 3*x**2 + 2

print(f"x = {x}")
print(f"y = {y}")

# Compute the gradients
y.backward()

# The gradient is now stored in x.grad
print(f"dy/dx (x.grad) = {x.grad}") # Output should be 24.0

x = 4.0
y = 50.0
dy/dx (x.grad) = 24.0


When you are only evaluating your model (not training), you don't need gradients. You can wrap your code in `with torch.no_grad():` to save memory and computation.

In [ ]:
with torch.no_grad():
    # Operations inside this block will not be tracked
    z = y * 2
    print(f"\n'z' has no grad function: {z.grad_fn}")


'z' has no grad function: None


# 4. `torch.nn` - Building Neural Networks

`torch.nn` is PyTorch's core module for building neural networks.

## 4.1 nn.Module and Defining a Network

All of your network models should be classes that inherit from `torch.nn.Module`. A custom `nn.Module` has two essential parts:

1.  `__init__(self)`: The constructor. This is where you define and initialize all the layers your network will use (e.g., convolutional layers, linear layers).
2.  `forward(self, x)`: The forward pass. This is where you define the computation, taking the input `x` and passing it through the layers you defined in `__init__`.

## 4.2 Common Layers

* `nn.Linear(in_features, out_features)`: A fully connected (dense) layer.
* `nn.Conv2d(in_channels, out_channels, kernel_size, stride=1, padding=0)`: A 2D convolution layer, essential for images.
* `nn.ReLU()`: The Rectified Linear Unit activation function. A non-linear function that is typically applied after Conv or Linear layers.
* `nn.MaxPool2d(kernel_size, stride=None)`: A 2D max pooling layer, used to downsample and reduce spatial dimensions.
* `nn.CrossEntropyLoss()`: A loss function that is very common for multi-class classification tasks. It handily combines `nn.LogSoftmax` and `nn.NLLLoss`.

## 4.3 A Simple Network:

In [ ]:
import torch.nn as nn
import torch.nn.functional as F # Contains activation functions like relu

class SimpleNet(nn.Module):
    def __init__(self):
        # Call the constructor of the parent class (nn.Module)
        super(SimpleNet, self).__init__()

        # --- Define Layers ---
        # 1 input image channel (grayscale), 6 output channels, 5x5 square kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        # 6 input channels, 16 output channels, 5x5 square kernel
        self.conv2 = nn.Conv2d(6, 16, 5)

        # --- Fully connected layers ---
        # The input size (16*5*5) is calculated from the conv/pool layers
        # We'll see how to calculate this in the full example
        self.fc1 = nn.Linear(16*5*5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10) # 10 output classes (digits 0-9)

    def forward(self, x):
        # --- Define Computation Flow ---
        # Convolution -> ReLU -> Max Pooling
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # Convolution -> ReLU -> Max Pooling
        x = F.max_pool2d(F.relu(self.conv2(x)), 2) # (2, 2) can be just 2

        # Flatten the tensor for the fully connected layers
        # The -1 infers the batch size
        x = x.view(-1, 16 * 5 * 5)

        # Fully connected -> ReLU
        x = F.relu(self.fc1(x))
        # Fully connected -> ReLU
        x = F.relu(self.fc2(x))
        # Output layer (no activation here, CrossEntropyLoss will apply it)
        x = self.fc3(x)
        return x

# Let's create an instance of this network
net = SimpleNet()
print(net)

SimpleNet(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


Let's generate output using this network.

In [ ]:
# Create a dummy input tensor (batch size of 1, 1 input channel, 32x32 image size)
dummy_input = torch.randn(1, 1, 32, 32) # Batch size 1, 1 channel, 32x32 image

# Pass the dummy input through the network
output = net(dummy_input)

print(f"Input tensor shape: {dummy_input.shape}")
print(f"Output tensor shape: {output.shape}")
print(f"Output:\n {output}")

Input tensor shape: torch.Size([1, 1, 32, 32])
Output tensor shape: torch.Size([1, 10])
Output:
 tensor([[ 0.0910, -0.0692, -0.1765,  0.1319, -0.0691,  0.1435,  0.0856,  0.0783,
          0.0831,  0.0740]], grad_fn=<AddmmBackward0>)


# 5. Datasets and DataLoaders

## 5.1 Challenges

You have a large dataset (e.g., 60,000 images). You can't load it all into memory at once, and you can't pass it all through your network at once. You need to:

1.  Load data in small **batches** (e.g., 64 images at a time).
2.  **Shuffle** the data at the beginning of every training epoch to prevent the model from learning the order of the data.
3.  **Preprocess** the data (e.g., convert images to Tensors, normalize pixel values).
4.  Do this efficiently using multiple CPU cores in **parallel**.

## 5.2 DataLoader

PyTorch elegantly solves this with two classes:

1.  `torch.utils.data.Dataset`: An abstract class that stores the samples and their corresponding labels. `torchvision.datasets` has many pre-built datasets (like MNIST, CIFAR-10).
2.  `torch.utils.data.DataLoader`: A wrapper around a `Dataset` that provides an iterator to easily loop over data in batches, with shuffling and parallel loading.

We also use `torchvision.transforms` to define a "pipeline" of preprocessing steps.

* `transforms.ToTensor()`: Converts a PIL (Python Imaging Library) Image or NumPy array into a PyTorch Tensor.
* `transforms.Normalize(mean, std)`: Normalizes a tensor's values. For an image, it normalizes each channel.


# 6. Full Example - MNIST Classification

We will now train a Convolutional Neural Network (CNN) to classify the 10 handwritten digits (0-9) from the MNIST dataset.

## 6.1 Configuration

First, let us now import the modules we need.

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

Next, we will test if the GPU is available.

In [ ]:
# Use GPU if available, otherwise CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cuda


Basic neural network training involves the following hyperparameters.

In [ ]:
# --- Hyperparameters ---
LEARNING_RATE = 0.001
BATCH_SIZE = 64
EPOCHS = 5

## 6.2 Load & Preprocess MNIST Data

The MNIST dataset is arguably the most famous and foundational benchmark in the field of machine learning and computer vision. Often described as the "Hello, World!" of deep learning, it serves as the classic introductory problem for image classification. The dataset is comprised of 70,000 small, 28x28 pixel grayscale images of handwritten digits, from 0 to 9. It is pre-divided into a training set of 60,000 images and a test set of 10,000 images, providing a standard way for researchers and students alike to train models and reliably benchmark their performance. Its simplicity, clean formatting, and relatively small size make it the perfect starting point for anyone learning to build and test their first neural networks.

In [ ]:
from IPython.display import Image, display
display(Image(url='https://upload.wikimedia.org/wikipedia/commons/b/b1/MNIST_dataset_example.png'))

We begin by defining an image transformation pipeline that converts images into the tensor format and standardizes their pixel values.

In [ ]:
# 1. Convert image to PyTorch Tensor
# 2. Normalize pixel values.
# (0.1307,) and (0.3081,) are the pre-calculated mean and std dev of MNIST
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

Defining the DataLoader is the next key step in our data processing. The setup details are slightly different than for a custom dataset because the MIST dataset is built into PyTorch.

In [ ]:
# --- Load Datasets ---
# download=True will download the data if it's not in the 'data/' directory
train_dataset = datasets.MNIST(
    root='data',
    train=True,
    transform=transform,
    download=True
)

test_dataset = datasets.MNIST(
    root='data',
    train=False,
    transform=transform,
    download=True
)

# --- Create DataLoaders ---
train_loader = DataLoader(
    dataset=train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True # Shuffle training data
)

test_loader = DataLoader(
    dataset=test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False # No need to shuffle test data
)

print(f"Loaded {len(train_dataset)} training images")
print(f"Loaded {len(test_dataset)} test images")

100%|██████████| 9.91M/9.91M [00:00<00:00, 38.6MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 1.02MB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 9.60MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 10.6MB/s]

Loaded 60000 training images
Loaded 10000 test images


## 6.3 Define the Model

We'll use a slightly different (and common) CNN architecture. MNIST images are `1x28x28` (Channel x Height x Width).

In [ ]:
class MNIST_CNN(nn.Module):
    def __init__(self):
        super(MNIST_CNN, self).__init__()
        # --- Conv Layer 1 ---
        # Input: 1x28x28
        # Output: 32x28x28 (using padding=1 to keep size)
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=32, kernel_size=3, stride=1, padding=1)

        # --- Max Pool Layer 1 ---
        # Input: 32x28x28
        # Output: 32x14x14 (kernel_size=2 halves dimensions)
        self.pool1 = nn.MaxPool2d(kernel_size=2, stride=2)

        # --- Conv Layer 2 ---
        # Input: 32x14x14
        # Output: 64x14x14 (using padding=1 to keep size)
        self.conv2 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, stride=1, padding=1)

        # --- Max Pool Layer 2 ---
        # Input: 64x14x14
        # Output: 64x7x7
        self.pool2 = nn.MaxPool2d(kernel_size=2, stride=2)

        # --- Fully Connected Layer ---
        # Input: 64 * 7 * 7 = 3136
        # Output: 10 (for 10 classes)
        self.fc1 = nn.Linear(64*7*7, 10)

    def forward(self, x):
        # Conv 1 -> ReLU -> Pool 1
        x = self.pool1(F.relu(self.conv1(x)))
        # Conv 2 -> ReLU -> Pool 2
        x = self.pool2(F.relu(self.conv2(x)))

        # Flatten the output for the FC layer
        # -1 infers the batch size
        x = x.view(-1, 64 * 7 * 7)

        # FC Layer
        x = self.fc1(x)
        # Note: We don't apply softmax here because
        # nn.CrossEntropyLoss does it for us.
        return x

print(MNIST_CNN())

MNIST_CNN(
  (conv1): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (pool1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (pool2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (fc1): Linear(in_features=3136, out_features=10, bias=True)
)


## 6.4 Initialize Model, Loss, and Optimizer

We also need some basic settings. This setup begins by creating an instance of the model and moving it to the specified device, such as a GPU, for accelerated computation.

In [ ]:
# Create an instance of the model
model = MNIST_CNN()
# Move the model's parameters to the selected device (GPU or CPU)
model.to(device)

MNIST_CNN(
  (conv1): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (pool1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (pool2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (fc1): Linear(in_features=3136, out_features=10, bias=True)
)

It then defines the loss function as nn.CrossEntropyLoss, the standard choice for multi-class classification tasks.

In [ ]:
criterion = nn.CrossEntropyLoss()

Finally, it initializes the Adam optimizer, a popular algorithm, providing it the model's parameters and the LEARNING_RATE to control the update steps.

In [ ]:
optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)

## Step 6: The Training Loop

The training loop is very similar to the previous examples.

In [ ]:
# Loop for the specified number of epochs
for epoch in range(EPOCHS):
    # Set the model to training mode
    # This is important for layers like Dropout or BatchNorm
    model.train()

    # Loop over the training data in batches
    # batch_idx provides a running count
    # (data, target) is a batch from the train_loader
    for batch_idx, (data, target) in enumerate(train_loader):
        # 1. Move data and target tensors to the device (GPU/CPU)
        data, target = data.to(device), target.to(device)

        # 2. Zero the gradients
        # We need to do this on every batch because PyTorch
        # accumulates gradients by default.
        optimizer.zero_grad()

        # 3. Forward Pass
        # Pass the data through the model
        output = model(data)

        # 4. Calculate Loss
        # Compare the model's output with the true target labels
        loss = criterion(output, target)

        # 5. Backward Pass
        # Compute the gradients of the loss w.r.t. model parameters
        loss.backward()

        # 6. Update Weights
        # Tell the optimizer to adjust the weights based on the gradients
        optimizer.step()

        # Print training status
        if batch_idx % 100 == 0:
            print(f"Epoch: {epoch+1}/{EPOCHS} | Batch: {batch_idx}/{len(train_loader)} | Loss: {loss.item():.4f}")

Epoch: 1/5 | Batch: 0/938 | Loss: 2.3408
Epoch: 1/5 | Batch: 100/938 | Loss: 0.1911
Epoch: 1/5 | Batch: 200/938 | Loss: 0.1941
Epoch: 1/5 | Batch: 300/938 | Loss: 0.1670
Epoch: 1/5 | Batch: 400/938 | Loss: 0.1611
Epoch: 1/5 | Batch: 500/938 | Loss: 0.0569
Epoch: 1/5 | Batch: 600/938 | Loss: 0.0232
Epoch: 1/5 | Batch: 700/938 | Loss: 0.0372
Epoch: 1/5 | Batch: 800/938 | Loss: 0.1542
Epoch: 1/5 | Batch: 900/938 | Loss: 0.0103
Epoch: 2/5 | Batch: 0/938 | Loss: 0.0241
Epoch: 2/5 | Batch: 100/938 | Loss: 0.0355
Epoch: 2/5 | Batch: 200/938 | Loss: 0.0123
Epoch: 2/5 | Batch: 300/938 | Loss: 0.1429
Epoch: 2/5 | Batch: 400/938 | Loss: 0.0065
Epoch: 2/5 | Batch: 500/938 | Loss: 0.0099
Epoch: 2/5 | Batch: 600/938 | Loss: 0.2041
Epoch: 2/5 | Batch: 700/938 | Loss: 0.0159
Epoch: 2/5 | Batch: 800/938 | Loss: 0.0063
Epoch: 2/5 | Batch: 900/938 | Loss: 0.0167
Epoch: 3/5 | Batch: 0/938 | Loss: 0.2075
Epoch: 3/5 | Batch: 100/938 | Loss: 0.0033
Epoch: 3/5 | Batch: 200/938 | Loss: 0.0215
Epoch: 3/5 | Batc

## Step 7: The Evaluation Loop

To test the model's performance, we must use the `test_loader`. We can omit gradient calculations here. It is also important to note that we must calculate the classification metrics, while calculating the loss function value is not essential.

In [ ]:
# Set the model to evaluation mode
model.eval()

test_loss = 0
correct = 0

# Disable gradient calculations to save memory and compute
with torch.no_grad():
    # Loop over the test data
    for data, target in test_loader:
        data, target = data.to(device), target.to(device)

        # Get model output
        output = model(data)

        # Sum up batch loss
        test_loss += criterion(output, target).item()

        # Get the index of the max log-probability (our prediction)
        pred = output.argmax(dim=1, keepdim=True)

        # Compare predictions to true labels
        correct += pred.eq(target.view_as(pred)).sum().item()

# Calculate average loss and accuracy
test_loss /= len(test_loader.dataset)
accuracy = 100. * correct / len(test_loader.dataset)

print(f"\n--- Test Set Results ---")
print(f"Average loss: {test_loss:.4f}")
print(f"Accuracy: {correct}/{len(test_loader.dataset)} ({accuracy:.2f}%)")


--- Test Set Results ---
Average loss: 0.0007
Accuracy: 9880/10000 (98.80%)


## Step 8: Saving and Loading Model

If you are satisfied with the model's performance, you can save the model locally for future use. Here, we will use the .pt file format.

In [ ]:
# Save only the model's state (its parameters)
# This is the recommended way.
torch.save(model.state_dict(), "mnist_cnn_model.pt")

print("\nModel saved to 'mnist_cnn_model.pt'")


Model saved to 'mnist_cnn_model.pt'


Loading the model is also simple and direct. Note that you must first create a model instance, and then use the `load_state_dict` function to load the model parameters.

In [ ]:
loaded_model = MNIST_CNN()
loaded_model.load_state_dict(torch.load("mnist_cnn_model.pt"))

<All keys matched successfully>

With a simple configuration, you will be able to use this model for classification.

In [ ]:
loaded_model.to(device)
loaded_model.eval()

MNIST_CNN(
  (conv1): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (pool1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (pool2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (fc1): Linear(in_features=3136, out_features=10, bias=True)
)

In [ ]:
import random
from torchvision import transforms
from PIL import Image

# Get a random index from the test dataset
random_index = random.randint(0, len(test_dataset) - 1)

# Get the image and label from the test dataset
image, label = test_dataset[random_index]

# The image is already a tensor due to the dataset's transform, but we need to add a batch dimension
# and move it to the device for the model.
image = image.unsqueeze(0).to(device)

# Use the loaded model to predict the digit
loaded_model.eval() # Set the model to evaluation mode
with torch.no_grad(): # Disable gradient calculation
    output = loaded_model(image)

# Get the predicted class (the index with the highest probability)
predicted_label = output.argmax(dim=1, keepdim=True).item()

image_display = image.squeeze(0).cpu()
image_display = transforms.Normalize((-0.1307/0.3081,), (1/0.3081,))(image_display)
image_display = transforms.ToPILImage()(image_display)

# Display the image and labels
print(f"Actual Label: {label}")
print(f"Predicted Label: {predicted_label}")
display(image_display)

Actual Label: 8
Predicted Label: 8
