## Python For Machine Learning Fall 2025
---
# Multivariate Linear Regression

## Numpy for Multivariate Linear Regression

NumPy is a powerful library for numerical operations in Python. Its main feature is the `ndarray`, a multi-dimensional array object that is highly efficient for performing mathematical calculations. In machine learning, we'll use NumPy to handle our data, which is often represented as matrices and vectors.

In [2]:
import numpy as np

The most straightforward way to create a NumPy array is to pass a Python list or tuple to the `np.array()` function. This is especially useful for creating arrays with specific initial values. Create a 1D array (vector)

In [53]:
a = np.array([1, 2, 3])
print("Vector:", a)
print("Shape:", a.shape)

Vector: [1 2 3]
Shape: (3,)


To create a multi-dimensional array, pass a nested list or tuple.

In [54]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print("\nMatrix:\n", b)
print("Shape:", b.shape)


Matrix:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)


NumPy provides several functions for creating arrays with placeholder or structured data. These are more efficient than creating Python lists first, especially for large arrays.

`np.zeros()`: Creates an array filled with zeros. You must specify the shape.

In [55]:
placeholder_array = np.zeros((3, 4), dtype=int)

placeholder_array[0, 1] = 10
placeholder_array[2, 3] = 20
print("\nPopulated array:\n", placeholder_array)


Populated array:
 [[ 0 10  0  0]
 [ 0  0  0  0]
 [ 0  0  0 20]]


`np.ones()`: Creates an array filled with ones.

In [6]:
placeholder_array_ones = np.ones((2, 3), dtype=float)
print("Placeholder array of ones:\n", placeholder_array_ones)

Placeholder array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]]


`np.full()`: Creates an array of a given shape filled with a specified value.

`np.eye()`: Creates a 2-D identity matrix, which has ones on the main diagonal and zeros elsewhere.

In [7]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


`np.identity(n)`: Used only for creating a square identity matrix.

In [8]:
identity_matrix_2 = np.identity(3)
print(identity_matrix_2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


np.diag() is a NumPy function that either extracts a diagonal from a 2D array or creates a 2D diagonal array from a 1D array.

In [9]:
identity_matrix_3 = np.diag([1, 1, 1])
print(identity_matrix_3)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


There are three common ways to transpose a NumPy matrix.

`.T` attribute

In [10]:
identity_matrix_T = np.array([[1, 2, 3], [4, 5, 6]]).T
print(identity_matrix_T)

[[1 4]
 [2 5]
 [3 6]]


`.transpose()` method

In [56]:
identity_matrix_T = np.array([[1, 2, 3], [4, 5, 6]]).transpose()
print(identity_matrix_T)

[[1 4]
 [2 5]
 [3 6]]


`np.transpose()` function

In [11]:
transposed = np.transpose(np.array([[1, 2, 3], [4, 5, 6]]))
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


`np.linalg.inv()` is a NumPy function used to calculate the multiplicative inverse of a matrix.

In [12]:
m = np.array([[1, 2],[3, 4]])
inverse_m = np.linalg.inv(m)
print(inverse_m)

[[-2.   1. ]
 [ 1.5 -0.5]]


In Numpy, you can perform matrix multiplication using either the `@` operator or the `np.matmul()` function.

In [13]:
result = np.matmul(m, inverse_m)
print(result)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [14]:
result = m @ inverse_m
print(result)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In Numpy, you can perform element-wise multiplication using the operator * or the np.multiply() function.

In [15]:
result = np.multiply(m, inverse_m)
print(result)

[[-2.   2. ]
 [ 4.5 -2. ]]


In [16]:
result = m * inverse_m
print(result)

[[-2.   2. ]
 [ 4.5 -2. ]]


`np.concatenate()` function or its convinient object `np.c_` can concatenate two or more Numpy arrays.

In [58]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.concatenate((arr1, arr2))

For 2D arrays, you must specify the `axis` to control whether the arrays are stacked vertically (along rows) or horizontally (along columns).

In [57]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

result = np.concatenate((arr1, arr2), axis=0)

For an Numpy array, method `.reshape()` returns a new array with the same data but a different shape.

In [62]:
arr1 = np.array([[1, 2], [3, 4]])
arr1.reshape(1, 4)

array([[1, 2, 3, 4]])

A very useful feature of .reshape() is the use of -1 as a placeholder. This tells NumPy to automatically calculate the dimension for that axis based on the total number of elements and the other dimensions you've specified.

In [63]:
arr1 = np.array([[1, 2], [3, 4]])
print(arr1.reshape(-1, 1))
print(arr1.reshape(1, -1))

[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]


Now we have everything we need to finish the calculation fo multivariable linear regression.

## From univariate to Multivariate Linear Regression

Recall that univariate linear regression uses a single feature to predict a target variable, described by the equation:

$$
y = m x + b
$$

But what happens when the target is influenced by multiple factors? We extend our model to **Multiple Linear Regression**, the single output version of **Multivariate linear regression**, where the equation becomes:

$$
y = \theta_0 + \theta_1 x_1 + \theta_2 x_2 + \dots + \theta_n x_n
$$

Here, $y$ is the target value, $\theta_0$ is the intercept, and $\theta_1, \dots, \theta_n$ are the coefficients (weights) for each feature $x_1, \dots, x_n$.

### Agreement on Symbols

To prevent confusion, we need to establish more precise symbol conventions, which is different from how we handle single-variable situations.

- We represent scalars with lowercase letters or Greek letters, such as $t$ or $\alpha$.
- Use bold, lowercase letters or bold Greek letters for vectors, like $\mathbf{x}$. Their elements are written as $x_i$. Note that a bold lowercase letter with a subscript, such as $\mathbf{x_1}$ and $\mathbf{x_2}$, represents two different constant vectors. By default, vectors are column vectors; a row vector is a transpose of a column vector, written as $\mathbf{x^T}$.
- Matrices are represented by capital letters such as $A$ and $\Sigma$. Their elements are shown with lowercase letters, such as $a_{ij}$. Capital letters with subscripts, like $A_1$ and $A_2$, indicate different constant matrices.

## The Matrix Form

Multiple linear regression has vectors as samples and the weights are also vectors. To handle the more complex model, the more compact **matrix form** is a better way.

Let's define our matrices:

-   **Feature Matrix $X$:** An $m \times (n+1)$ matrix where $m$ is the number of training examples and $n$ is the number of features. We add a column of ones for the intercept term $\theta_0$.
-   **Coefficient Vector $\theta$:** A vector of size $(n+1) \times 1$ containing all the coefficients, including the intercept.
-   **Target Vector $y$:** An $m \times 1$ vector of the target values.

The prediction can then be calculated as a dot product:

$$
\hat{y} = X \theta
$$

## Data Preparation

We will use a typical house price prediction model for this experiment. https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html

In [25]:
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
print(housing.data.shape, housing.feature_names)

(20640, 8) ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']


To start, we will select a few features from the dataset.

In [31]:
X = housing.data[:, 1:4]
print(X.shape, housing.feature_names[1:4])

(20640, 3) ['HouseAge', 'AveRooms', 'AveBedrms']


Next, we will add a column where all values are 1.

In [35]:
X_full = np.c_[np.ones((X.shape[0], 1)), X]
print(X_full.shape)

(20640, 4)


The last step is to process the prediction target.

In [30]:
y = housing.target.reshape(-1, 1)
print(y.shape, housing.target_names)

(20640, 1) ['MedHouseVal']


The model is very compact when represented in its matrix form.

In [34]:
def predict(feature, theta):
    return feature @ theta

theta_hat = np.array([[1], [2], [3], [4]])
print(predict(X_full, theta_hat).shape)

(20640, 1)


## The Normal Equation

The **Normal Equation** provides a direct, analytical solution to find the optimal values for $\theta$ without needing to iterate. The formula is:

$$
\mathbf{\theta} = (X^T X)^{-1} X^T \mathbf{y}
$$

Where:
-   $X^T$ is the transpose of the feature matrix $X$.
-   $X^T X$ is the dot product of the transpose of $X$ and $X$.
-   $(X^T X)^{-1}$ is the inverse of that result.
-   $\mathbf{y}$ is the target vector.


Here is how we get the result
Note that the linear function (model) as follows:
$$
h_{\mathbf{\theta}}(x_1, x_2,..., x_n) = \theta_0\cdot 1+\theta_1x_1+,...,\theta_nx_n
$$
Note $\mathbf{x}=[x_1, x_2,..., x_n]$, then we have:
$$
h_{\mathbf{\theta}}(\mathbf{x})=\mathbf{x}\mathbf{\theta}
$$
Note that:
$$
X= \begin{matrix} \mathbf{x_1^T} \\ \mathbf{x_2^T} \\ ... \\ \mathbf{x_m^T} \end{matrix}
$$
We can simplify the calculation as
$$
\mathbf{y}=X\mathbf{\theta}
$$
Then we can define the loss function as:
$$
J(\mathbf{\theta})=\frac{1}{2}(X\mathbf{\theta}-\mathbf{y})^T(X\mathbf{\theta}-\mathbf{y})
$$
Make the derivate of $J$ regarding $\mathbf{\theta}$ equals to $0$, we get
$$
\frac{\partial}{\partial \mathbf{\theta}}J(\mathbf{\theta})=X^T(X\mathbf{\theta}-\mathbf{y})=0
$$
Thus, we get:
$$
\mathbf{\theta}=(X^T X)^{-1} X^T \mathbf{y}
$$

Calculate coefficients using the Normal Equation
Using np.linalg.inv for matrix inversion and @ for dot product

In [64]:
theta_best = np.linalg.inv(X_full.T @ X_full) @ X_full.T @ y

print("Coefficients (Theta_best):")
print(theta_best)

Coefficients (Theta_best):
[[ 1.52346805]
 [ 0.0153096 ]
 [ 0.34146565]
 [-1.59316623]]


Let's check if the predictions are accurate.

In [65]:
preds = predict(X_full, theta_best)

for pred, gt in zip(preds[:5], y[:5]):
    print(f"Prediction: {pred}, Ground Truth: {gt}")

Prediction: [2.90490224], Ground Truth: [4.526]
Prediction: [2.42671195], Ground Truth: [3.585]
Prediction: [3.43950228], Ground Truth: [3.521]
Prediction: [2.59643092], Ground Truth: [3.413]
Prediction: [2.74226235], Ground Truth: [3.422]


Let's see if `sklearn` performs better.

In [66]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X, y)

preds = model.predict(X)
for pred, gt in zip(preds[:5], y[:5]):
    print(f"Prediction: {pred}, Ground Truth: {gt}")

Prediction: [2.90490224], Ground Truth: [4.526]
Prediction: [2.42671195], Ground Truth: [3.585]
Prediction: [3.43950228], Ground Truth: [3.521]
Prediction: [2.59643092], Ground Truth: [3.413]
Prediction: [2.74226235], Ground Truth: [3.422]


Gradient Descent

The problem can also be solved using gradient descent (of course). Slightly different from the normal equation, we have:
$$
J(\mathbf{\theta})=\frac{1}{2}(X\mathbf{\theta}-\mathbf{y})^T(X\mathbf{\theta}-\mathbf{y})
$$
and thus, the gradient vector is:
$$
\frac{\partial}{\partial \mathbf{\theta}}J(\mathbf{\theta})=\frac{1}{m}X^T(X\mathbf{\theta}-\mathbf{y})
$$



Similar to the univariate linear regression, we implement the algorithm block by block.

We will implement the loss function first, following the same basic steps as single-variable linear regression.

In [67]:
def cost_function(X, y, theta):
    m = len(y)
    predictions = X @ theta
    cost = (1/(2*m)) * np.sum(np.square(predictions - y))
    return cost

The next step is to implement how to calculate the gradient.

In [68]:
def gradient(X, y, theta):
    m = len(y)
    predictions = X @ theta
    grad = (1/m) * X.T @ (predictions - y)
    return grad

Initialize the model's parameters randomly.

In [69]:
theta_init = np.random.randn(X_full.shape[1], 1)
print(theta_init)

[[0.04190765]
 [1.01251601]
 [0.30311072]
 [0.80913413]]


Define the hyperparameters and implement the training loop.

In [70]:
learning_rate = 0.0001
n_iterations = 1000
theta = theta_init
cost_history = []
theta_history = []

for _ in range(n_iterations):
    grad = gradient(X_full, y, theta)
    theta = theta - learning_rate * grad
    cost = cost_function(X_full, y, theta)
    cost_history.append(cost)
    theta_history.append(theta)

print("Coefficients (Theta_best) from Gradient Descent:")
print(theta)

Coefficients (Theta_best) from Gradient Descent:
[[0.01619291]
 [0.02552998]
 [0.07965402]
 [0.75192994]]


Let's evaluate the model's performance.

In [71]:
preds = predict(X_full, theta)

for pred, gt in zip(preds[:5], y[:5]):
    print(f"Prediction: {pred}, Ground Truth: {gt}")

Prediction: [2.38906896], Ground Truth: [4.526]
Prediction: [1.78000125], Ground Truth: [3.585]
Prediction: [2.81109167], Ground Truth: [3.521]
Prediction: [2.61399282], Ground Truth: [3.413]
Prediction: [2.65702402], Ground Truth: [3.422]


## Normal Equation vs. Gradient Descent

-   **Normal Equation:**
    -   **Pros:** Direct solution, no need to choose a learning rate or number of iterations.
    -   **Cons:** Computationally expensive for large datasets ($O(n^3)$ due to matrix inversion).

-   **Gradient Descent:**
    -   **Pros:** More scalable for large datasets.
    -   **Cons:** Requires tuning hyperparameters like learning rate and number of iterations.

For many real-world problems, especially with massive datasets, libraries like scikit-learn use optimized algorithms (often based on gradient descent) for efficiency.